services:
  translator:
    build: ./translator
    ports:
      - "5000:80"
    volumes:
      - ./translator/app:/src/app

  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./side-web/tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password

  app:
    build: ./side-web
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./side-web:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
      - translator
      - redis

  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ./side-web/tmp/redis:/data
