services:
  elastic-search:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    container_name: elastic-search
    environment:
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
